apiVersion: v1
kind: Pod
metadata:
  name: test-project-volume
  labels:
    app: test-project-volume
spec:
  containers:
    - name: test-project-volume
      image: busybox
      imagePullPolicy: IfNotPresent
      args:
        - sleep
        - "36000"
      volumeMounts:
        - mountPath: /projected-volume
          name: mysecret
  restartPolicy: Always
  volumes:
    - name: mysecret
      secret:
        secretName: mysecret


