apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngxin-deployment
  labels:
    app: ngxin-deployment
spec:
  selector:
    matchLabels:
      app: nginx-deploy
  replicas: 1
  template:
    metadata:
      name: ngxin-deployment
      labels:
        app: nginx-deploy
    spec:
      restartPolicy: Always
      hostAliases:
        - ip: 127.0.0.1
          hostnames:
            - foo.remote
      containers:
        - name: nginx-deploy
          image: nginx:latest
          ports:
            - containerPort: 80 # 仅仅是一个声明
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: nginx-vol
      volumes:
        - name: nginx-vol
          hostPath:
            path: /tmp/data


