apiVersion: v1
kind: Pod
metadata:
  name: redis-lifecycle
  labels:
    app: redis-lifecycle
spec:
  containers:
    - name: redis-lifecycle
      image: redis:5.0
      imagePullPolicy: IfNotPresent
      lifecycle:
        postStart:
          exec:
            command:
              - /bin/bash
              - -c
              - echo hello postStart
        preStop:
          exec:
            command: ["/bin/bash","-c","echo '================'"]

  restartPolicy: Always
