apiVersion: v1
kind: Pod
metadata:
  name: test-liveness
  labels:
    app: test-liveness
spec:
  containers:
    - name: test-liveness
      image: busybox
      imagePullPolicy: IfNotPresent
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
  restartPolicy: Always # default value
#  默认是会重启的，但是一直在同一个node上，除非手动修改，如果这个node宕了也不会调度到另一个node，
#  所以更推荐单个副本的deployment，而不是pod
# 10.1.0.32