apiVersion: v1
kind: Pod
metadata:
  name: test-liveness
  labels:
    app: test-liveness
spec:
  containers:
    - name: test-liveness
      image: busybox
      imagePullPolicy: IfNotPresent
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
  restartPolicy: Always # default value
# 10.1.0.32