apiVersion: v1
kind: Pod
metadata:
  name: nginx-nginx
  labels:
    app: nginx
spec:
  hostAliases:
    - ip: 127.0.0.1
      hostnames:
        - www.foo.com
        - www.bar.com
  containers:
    - env:
        - name: NGINX_CONF_PATH
          value: /etc/nginx
    - name: nginx-1
      image: nginx
      imagePullPolicy: IfNotPresent
    - name: nginx-2
      image: nginx
      imagePullPolicy: IfNotPresent
  restartPolicy: Always


