apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    owner: panligang
spec:
  hostAliases:
    - ip: 127.0.0.1
      hostnames:
        - www.foo.com
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
