apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
    owner: panligang
spec:
  hostAliases:
    - ip: 127.0.0.1
      hostnames:
        - www.foo.com
        - www.bar.com
  containers:
    - name: redis
      image: redis:5.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 6379
          hostPort: 6380
  restartPolicy: Always


