apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: redis-ds
  labels:
    app: redis-ds
spec:
  selector:
    matchLabels:
      app: redis-ds
  template:
    metadata:
      name: redis-ds
      labels:
        app: redis-ds
    spec:
      containers:
        - name: redis
          image: redis:5.0
          ports:
            - containerPort: 6379
          imagePullPolicy: IfNotPresent
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
          operator: Exists

# DaemonSet: 每个node上运行这样一个pod，有新的node加入集群，pod也会自动部署到新的node上，当旧节点删除后，上面的pod也会被回收掉。


