apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: redis-ds
  labels:
    app: redis-ds
spec:
  selector:
    matchLabels:
      app: redis-ds
  template:
    metadata:
      name: redis-ds
      labels:
        app: redis-ds
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          imagePullPolicy: IfNotPresent
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
          operator: Exists


