apiVersion: v1
kind: Pod
metadata:
  name: test-configmap2
  labels:
    app:  test-configmap2
spec:
  containers:
    - name:  test-configmap
      image: busybox
      imagePullPolicy: IfNotPresent
      args:
        - sleep
        - "36000"
      volumeMounts:
        - mountPath: /projected-volume
          name: myconfigmap
  restartPolicy: Always
  volumes:
    - name: myconfigmap
      configMap:
        name: myconfigmap
  dnsPolicy: ClusterFirst



