apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    app: ngx-deploy
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
#  clusterIP: None
  type: ClusterIP #默认