
# 由运维定义的持久化卷，事先在k8s集群中创建好
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 172.16.1.4
    path: "/nfs"