apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
  - name: redis
    image: redis:5.0
    volumeMounts:
      - mountPath: /data
        name: nfs
  volumes:
    - name: nfs
      persistentVolumeClaim:
        claimName: nfs
